name: Publish Jar

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: 'ubuntu-latest'

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
          cache: maven
          server-id: ossrh
          server-username: MY_MAVEN_USERNAME
          server-password: MY_MAVEN_PASSWORD
      - name: Publish package
        run: mvn --batch-mode deploy
        env:
          MAVEN_USERNAME: ${{ secrets.MY_MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MY_MAVEN_PASSWORD }}
      

