name: Tests

on:
  push:
    branches: 
      - master
      - main
  pull_request:

jobs:
  tests:
    strategy:
      matrix:
        java_version:
          - '8'
          - '11'
          # TODO: Fix for java version 17
          # - '17'
    runs-on: 'ubuntu-latest'

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '${{ matrix.java_version }}'
          cache: maven
      - run: mvn clean test

